import type { AppProps } from "next/app";
import { GlobalStyles } from "@/styles/Globalstyles";
import { ThemeProvider } from "styled-components";
import MainTheme from "@/styles/Theme";
import Head from "next/head";
import { ReactElement, ReactNode } from "react";
import { NextPage } from "next";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout || ((page) => page);

  return (
    <ThemeProvider theme={MainTheme}>
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <GlobalStyles />

      {getLayout(<Component {...pageProps} />)}
    </ThemeProvider>
  );
}

export default MyApp;
